-- F5: Persisted anomaly detections
-- Stores per-workspace anomaly events generated by AnomalyDetectionService
-- so they survive process restarts and can be filtered/acknowledged.

CREATE TABLE IF NOT EXISTS public.detected_anomalies (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID NOT NULL,
    tenant_id       UUID NOT NULL,
    anomaly_type    VARCHAR(50)  NOT NULL,        -- pass_rate_drop | volume_anomaly | failure_spike
    severity        VARCHAR(20)  NOT NULL,        -- Critical | High | Medium | Low
    -- Where the anomaly was observed
    dataset         VARCHAR(255),
    column_name     VARCHAR(255),
    rule_id         UUID,                          -- nullable: not all anomaly types tie to a rule
    -- Human-readable description
    summary         TEXT NOT NULL,
    current_value   VARCHAR(255),
    expected_value  VARCHAR(255),
    deviation       VARCHAR(255),
    -- Lifecycle
    status          VARCHAR(20)  NOT NULL DEFAULT 'open',  -- open | acknowledged | resolved | suppressed
    detected_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    acknowledged_by UUID,
    resolved_at     TIMESTAMP WITH TIME ZONE,
    resolved_by     UUID,
    notes           TEXT,
    -- Dedup helper: same (workspace, type, dataset, column, rule) within a short window
    -- avoids inserting duplicates each time the detector runs.
    fingerprint     TEXT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS detected_anomalies_workspace_idx
    ON public.detected_anomalies (workspace_id, detected_at DESC);

CREATE INDEX IF NOT EXISTS detected_anomalies_workspace_status_idx
    ON public.detected_anomalies (workspace_id, status, detected_at DESC);

CREATE INDEX IF NOT EXISTS detected_anomalies_fingerprint_idx
    ON public.detected_anomalies (workspace_id, fingerprint, detected_at DESC);
