"""Pydantic schemas for the Unified Proposal Engine (F111)."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class ProposalStatus(str, Enum):
    pending = "pending"
    confirmed = "confirmed"
    rejected = "rejected"
    adjusted = "adjusted"


class ProposalRequest(BaseModel):
    """Request to generate a rule proposal from natural language."""

    prompt: str = Field(..., min_length=3, max_length=2000)
    dataset_context: str | None = Field(None, max_length=500)
    domain_context: str | None = Field(None, max_length=100)


class ProposalAdjustment(BaseModel):
    """A user adjustment to a proposal before confirmation."""

    field: str
    old_value: Any = None
    new_value: Any = None
    reason: str | None = None


class ProposalPayload(BaseModel):
    """The full proposal content generated by the engine (F128: typed fields)."""

    # F128: typed SIR fields (previously Dict[str, Any])
    # Lenient coercion: accepts both typed SIR models and raw dicts
    parsed_rule: Any | None = None
    resolved_rule: Any | None = None
    # F128: typed compiled checks (previously List[Dict])
    compiled_checks: Any | None = None
    glossary_matches: list[dict[str, Any]] = Field(default_factory=list)
    resolution_evidence: dict[str, Any] = Field(default_factory=dict)
    parse_confidence: float = 0.0
    resolution_confidence: float = 0.0

    @field_validator("parsed_rule", "resolved_rule", mode="before")
    @classmethod
    def _coerce_sir(cls, v: Any) -> Any:
        """Best-effort coercion of dict → StructuredIntermediateRepresentation."""
        if v is None or not isinstance(v, dict):
            return v
        # Import here to avoid circular imports (proposal → nl_rule_builder)
        from app.schemas.nl_rule_builder import StructuredIntermediateRepresentation

        # Only coerce if the dict has required SIR fields
        if "rule_type" in v and "subject" in v and "confidence" in v:
            try:
                return StructuredIntermediateRepresentation(**v)
            except Exception:
                return v  # Return raw dict on coercion failure
        return v  # Incomplete dict — keep as-is

    @field_validator("compiled_checks", mode="before")
    @classmethod
    def _coerce_compiled(cls, v: Any) -> Any:
        """Best-effort coercion of list[dict] → list[CompiledCheckConfig]."""
        if v is None or not isinstance(v, list):
            return v
        from app.schemas.nl_compiler import CompiledCheckConfig

        result = []
        for item in v:
            if isinstance(item, dict):
                try:
                    result.append(CompiledCheckConfig(**item))
                except Exception:
                    result.append(item)  # Keep raw dict on coercion failure
            else:
                result.append(item)
        return result


class ProposalResponse(BaseModel):
    """A rule proposal returned to the client."""

    proposal_id: UUID
    workspace_id: UUID
    created_by: str | None = None
    status: ProposalStatus = ProposalStatus.pending
    original_prompt: str
    proposal_payload: ProposalPayload
    adjustments: list[ProposalAdjustment] = Field(default_factory=list)
    generated_flow_id: UUID | None = None
    confidence: float = 0.0
    created_at: datetime
    updated_at: datetime


class ProposalListResponse(BaseModel):
    """Paginated list of proposals."""

    items: list[ProposalResponse]
    total: int


class ConfirmProposalRequest(BaseModel):
    """Request to confirm (and optionally adjust) a proposal."""

    adjustments: list[ProposalAdjustment] = Field(default_factory=list)
    create_flow: bool = False


class RejectProposalRequest(BaseModel):
    """Request to reject a proposal."""

    reason: str | None = Field(None, max_length=500)
