"""
Seed template library for all 8 DQ dimensions.

Each template is a dict matching RuleTemplate model columns.
The canonical_rule_template uses __PLACEHOLDER__ tokens replaced at apply time.

seed_all(db) is idempotent — existing templates (by name) are skipped.
"""

from typing import Any

from sqlalchemy.orm import Session

from app.models.rule_template import RuleTemplate

# ---------------------------------------------------------------------------
# COMPLETENESS TEMPLATES (7)
# ---------------------------------------------------------------------------

_COMPLETENESS_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "completeness",
        "name": "Mandatory Fields — NULL Check",
        "description": "Ensures specified columns contain no NULL values. Use for required fields like email, name, or ID.",
        "category": "completeness_basic",
        "tags": ["mandatory", "null_check", "required_fields"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 98.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IS NOT NULL",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "null",
                "threshold_pass": 100.0,
                "threshold_warn": 98.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "Non-Empty Text Fields",
        "description": "Checks that text columns are not NULL and not empty/whitespace. Use for name, address, description fields.",
        "category": "completeness_basic",
        "tags": ["empty", "whitespace", "text_fields"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IS NOT NULL AND NOT EMPTY",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "empty",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "Placeholder Detection",
        "description": "Detects placeholder values like N/A, TBD, -, UNKNOWN in columns. Useful for imported or manually-entered data.",
        "category": "completeness_advanced",
        "tags": ["placeholder", "data_cleansing", "import"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NOT IN placeholder values",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "placeholder",
                "placeholder_values": ["N/A", "TBD", "-", "UNKNOWN", "NULL", "NONE"],
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "Conditional Required Field",
        "description": "Column is required only when a condition is met. Example: state required when country = US.",
        "category": "completeness_advanced",
        "tags": ["conditional", "dependent_fields", "regional"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 98.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IS NOT NULL WHEN __COLUMN_2__ meets condition",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "conditional",
                "condition_column": "__COLUMN_2__",
                "condition_value": "__CONDITION_VALUE__",
                "threshold_pass": 100.0,
                "threshold_warn": 98.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "At Least One Contact Method",
        "description": "At least one of multiple contact columns must be populated. Use for CRM data requiring phone, mobile, or email.",
        "category": "completeness_advanced",
        "tags": ["multi_field", "contact", "crm"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "AT LEAST ONE of columns populated",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__", "__COLUMN_2__"],
                "check_mode": "multi_field",
                "multi_field_mode": "any",
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "Minimum Population Rate",
        "description": "Ensures a column is populated in at least a minimum percentage of rows. Use for optional-but-expected fields.",
        "category": "completeness_basic",
        "tags": ["population", "optional_fields", "coverage"],
        "default_severity": "low",
        "default_threshold_pass": 80.0,
        "default_threshold_warn": 60.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IS NOT NULL",
            "expectation": "80.0%",
            "severity": "low",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "population",
                "threshold_pass": 80.0,
                "threshold_warn": 60.0,
            },
        },
    },
    {
        "dimension": "completeness",
        "name": "Per-Partition Completeness",
        "description": "Checks completeness within each partition (group). Use when requirements differ by region, tenant, or category.",
        "category": "completeness_advanced",
        "tags": ["group", "partition", "segmented"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "completeness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IS NOT NULL per group",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "check_mode": "group",
                "group_by_columns": ["__COLUMN_2__"],
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# VALIDITY TEMPLATES (7)
# ---------------------------------------------------------------------------

_VALIDITY_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "validity",
        "name": "Status Enum Validation",
        "description": "Validates that a column contains only allowed status values. Use for order_status, account_status, etc.",
        "category": "validity_basic",
        "tags": ["enum", "status", "allowed_values"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "IN allowed values",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "allowed_values",
                "allowed_values": ["__ALLOWED_VALUE_1__", "__ALLOWED_VALUE_2__"],
                "case_sensitive": False,
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Numeric Range Check",
        "description": "Validates that numeric values fall within a specified range. Use for age, percentage, amount fields.",
        "category": "validity_basic",
        "tags": ["range", "numeric", "bounds"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "BETWEEN min and max",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "range",
                "min_value": 0,
                "max_value": 999999,
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Regex Pattern Match",
        "description": "Validates column values against a regular expression pattern. Use for phone numbers, zip codes, custom formats.",
        "category": "validity_advanced",
        "tags": ["regex", "pattern", "format"],
        "default_severity": "medium",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "MATCHES regex pattern",
            "expectation": "98.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "regex",
                "regex_pattern": "__REGEX_PATTERN__",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Reference Lookup Validation",
        "description": "Validates that column values exist in a reference table. Use for country_code, currency_code, category_id.",
        "category": "validity_advanced",
        "tags": ["reference", "lookup", "foreign_key"],
        "default_severity": "high",
        "default_threshold_pass": 99.0,
        "default_threshold_warn": 98.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "EXISTS IN reference table",
            "expectation": "99.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "reference_lookup",
                "reference_dataset": "__REF_TABLE__",
                "reference_column": "__REF_COLUMN__",
                "threshold_pass": 99.0,
                "threshold_warn": 98.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Business Rule Expression",
        "description": "Validates rows against a custom SQL boolean expression. Use for complex domain rules.",
        "category": "validity_advanced",
        "tags": ["business_rule", "custom", "expression"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "SATISFIES business rule",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "business_rule",
                "business_rule_expression": "__EXPRESSION__",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Cross-Field Comparison",
        "description": "Validates that one column relates correctly to another (e.g., start_date <= end_date). Use for date pairs, amount comparisons.",
        "category": "validity_advanced",
        "tags": ["cross_field", "comparison", "date_pair"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "__COLUMN__ <= __COLUMN_2__",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "cross_field",
                "comparison_column": "__COLUMN_2__",
                "comparison_operator": "<=",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "validity",
        "name": "Negative / Invalid Value Detection",
        "description": "Flags rows matching an expression as INVALID. Use to detect known bad patterns (e.g., negative amounts, test records).",
        "category": "validity_advanced",
        "tags": ["negative", "invalid", "detection"],
        "default_severity": "medium",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "validity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NOT matching negative expression",
            "expectation": "98.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "validation_type": "negative",
                "negative_expression": "__EXPRESSION__",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# UNIQUENESS TEMPLATES (6)
# ---------------------------------------------------------------------------

_UNIQUENESS_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "uniqueness",
        "name": "Primary Key Uniqueness",
        "description": "Ensures a single column has no duplicate values. Use for primary key columns like customer_id, order_id.",
        "category": "uniqueness_basic",
        "tags": ["primary_key", "pk", "identity"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": None,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NO DUPLICATES",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__"],
                "uniqueness_mode": "exact",
                "case_sensitive": True,
                "threshold_pass": 100.0,
            },
        },
    },
    {
        "dimension": "uniqueness",
        "name": "Composite Key Uniqueness",
        "description": "Ensures a combination of columns is unique. Use for compound keys like (vendor_id, invoice_number).",
        "category": "uniqueness_basic",
        "tags": ["composite_key", "compound", "multi_column"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": None,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__+__COLUMN_2__",
            "condition": "NO DUPLICATES on composite key",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__", "__COLUMN_2__"],
                "uniqueness_mode": "composite",
                "case_sensitive": True,
                "threshold_pass": 100.0,
            },
        },
    },
    {
        "dimension": "uniqueness",
        "name": "Scoped Uniqueness (Per Partition)",
        "description": "Ensures uniqueness within a scope/partition. Use for email unique per tenant, SKU unique per warehouse.",
        "category": "uniqueness_advanced",
        "tags": ["scoped", "partition", "per_tenant"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "UNIQUE within scope",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "uniqueness_mode": "scoped",
                "scope_columns": ["__COLUMN_2__"],
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "uniqueness",
        "name": "Cross-Dataset Value Exclusion",
        "description": "Ensures values in one column do NOT exist in another table's column. Use for detecting orphan references.",
        "category": "uniqueness_advanced",
        "tags": ["cross_dataset", "orphan", "exclusion"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NOT IN cross dataset",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "uniqueness_mode": "cross_dataset",
                "cross_dataset_name": "__REF_TABLE__",
                "cross_dataset_column": "__REF_COLUMN__",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "uniqueness",
        "name": "Fuzzy Duplicate Detection",
        "description": "Detects near-duplicate values using fuzzy matching (Levenshtein). Use for name, address, or title deduplication.",
        "category": "uniqueness_advanced",
        "tags": ["fuzzy", "deduplication", "levenshtein"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NO fuzzy duplicates",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "uniqueness_mode": "fuzzy",
                "fuzzy_algorithm": "levenshtein",
                "fuzzy_threshold": 0.85,
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
    {
        "dimension": "uniqueness",
        "name": "Temporal Uniqueness (Time Window)",
        "description": "Ensures values are unique within a time window. Use for preventing duplicate transactions within 24 hours.",
        "category": "uniqueness_advanced",
        "tags": ["temporal", "time_window", "transaction"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "uniqueness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "UNIQUE within time window",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "uniqueness_mode": "temporal",
                "temporal_column": "__COLUMN_2__",
                "temporal_window": "1d",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# CONFORMITY TEMPLATES (6)
# ---------------------------------------------------------------------------

_CONFORMITY_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "conformity",
        "name": "Email Format (RFC 5322)",
        "description": "Validates that email addresses conform to RFC 5322 standard. Use for email columns in customer/contact data.",
        "category": "conformity_standard",
        "tags": ["email", "rfc5322", "contact"],
        "default_severity": "high",
        "default_threshold_pass": 99.0,
        "default_threshold_warn": 97.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "CONFORMS TO email_rfc5322",
            "expectation": "99.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "standard",
                "standard_name": "email_rfc5322",
                "threshold_pass": 99.0,
                "threshold_warn": 97.0,
            },
        },
    },
    {
        "dimension": "conformity",
        "name": "ISO 8601 Date Format",
        "description": "Validates date/datetime strings conform to ISO 8601 standard. Use for imported date columns.",
        "category": "conformity_standard",
        "tags": ["date", "iso8601", "datetime"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "CONFORMS TO iso_8601",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "standard",
                "standard_name": "iso_8601",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "conformity",
        "name": "Phone Number Format (E.164)",
        "description": "Validates phone numbers conform to E.164 international standard. Use for phone/mobile columns.",
        "category": "conformity_standard",
        "tags": ["phone", "e164", "international"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "CONFORMS TO e164",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "standard",
                "standard_name": "e164",
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
    {
        "dimension": "conformity",
        "name": "ISO Country Code (ISO 3166)",
        "description": "Validates country codes conform to ISO 3166 standard. Use for country_code, billing_country columns.",
        "category": "conformity_standard",
        "tags": ["country", "iso3166", "geography"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "CONFORMS TO iso_3166",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "standard",
                "standard_name": "iso_3166",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "conformity",
        "name": "String Length Constraint",
        "description": "Validates string length falls within bounds. Use for fixed-length codes, zip codes, short names.",
        "category": "conformity_structural",
        "tags": ["length", "string", "constraint"],
        "default_severity": "medium",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "LENGTH within bounds",
            "expectation": "98.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "length",
                "min_length": 1,
                "max_length": 255,
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "conformity",
        "name": "Currency Code (ISO 4217)",
        "description": "Validates currency codes conform to ISO 4217 standard. Use for currency, payment_currency columns.",
        "category": "conformity_standard",
        "tags": ["currency", "iso4217", "financial"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "conformity",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "CONFORMS TO iso_4217",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "conformity_type": "standard",
                "standard_name": "iso_4217",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# CONSISTENCY TEMPLATES (5)
# ---------------------------------------------------------------------------

_CONSISTENCY_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "consistency",
        "name": "Intra-Record Column Agreement",
        "description": "Ensures two columns in the same row are consistent (e.g., city matches state). Use for address, classification data.",
        "category": "consistency_basic",
        "tags": ["intra_record", "column_agreement", "address"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "consistency",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "__COLUMN__ = __COLUMN_2__",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "consistency_type": "intra_record",
                "reference_column": "__COLUMN_2__",
                "expected_column": "__COLUMN__",
                "comparison_operator": "=",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "consistency",
        "name": "Formula Verification",
        "description": "Validates that a column equals a formula over other columns (e.g., line_total = qty * price). Use for financial data.",
        "category": "consistency_formula",
        "tags": ["formula", "calculation", "financial"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "consistency",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "__COLUMN__ = formula result",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "consistency_type": "formula",
                "expected_column": "__COLUMN__",
                "rule_expression": "__EXPRESSION__",
                "tolerance_type": "absolute",
                "tolerance_value": 0.01,
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "consistency",
        "name": "Date Sequence Check",
        "description": "Validates temporal ordering of date columns (e.g., created_at <= updated_at). Use for audit trails, order lifecycle.",
        "category": "consistency_temporal",
        "tags": ["temporal", "date_sequence", "ordering"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "consistency",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "__COLUMN__ <= __COLUMN_2__",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "consistency_type": "temporal",
                "comparison_column": "__COLUMN_2__",
                "comparison_operator": "<=",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "consistency",
        "name": "Cross-Table Consistency",
        "description": "Validates that values match between two tables joined on a key. Use for data warehouse fact/dimension consistency.",
        "category": "consistency_cross",
        "tags": ["cross_table", "join", "warehouse"],
        "default_severity": "high",
        "default_threshold_pass": 99.0,
        "default_threshold_warn": 98.0,
        "canonical_rule_template": {
            "dimension": "consistency",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "MATCHES cross-table value",
            "expectation": "99.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "consistency_type": "cross_table",
                "comparison_dataset": "__REF_TABLE__",
                "join_keys": ["__COLUMN_2__"],
                "comparison_columns": ["__COLUMN__"],
                "threshold_pass": 99.0,
                "threshold_warn": 98.0,
            },
        },
    },
    {
        "dimension": "consistency",
        "name": "Aggregation Sum Check",
        "description": "Validates that an aggregation (SUM/COUNT) of a column meets expectations. Use for batch totals, record counts.",
        "category": "consistency_aggregation",
        "tags": ["aggregation", "sum", "count"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "consistency",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "SUM(__COLUMN__) consistent",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "consistency_type": "aggregation",
                "expected_column": "__COLUMN__",
                "group_by_columns": ["__COLUMN_2__"],
                "aggregation_function": "SUM",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# TIMELINESS TEMPLATES (6)
# ---------------------------------------------------------------------------

_TIMELINESS_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "timeliness",
        "name": "Daily Data Freshness",
        "description": "Ensures the most recent record is no older than 24 hours. Use for operational tables updated daily.",
        "category": "timeliness_freshness",
        "tags": ["freshness", "daily", "operational"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": None,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "FRESHNESS <= 24h",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "freshness",
                "timestamp_column": "__COLUMN__",
                "max_age": "1d",
                "threshold_pass": 100.0,
            },
        },
    },
    {
        "dimension": "timeliness",
        "name": "Record Age Limit",
        "description": "Ensures individual records are not older than a specified age. Use for time-sensitive data like pricing, inventory.",
        "category": "timeliness_age",
        "tags": ["record_age", "stale", "expiry"],
        "default_severity": "medium",
        "default_threshold_pass": 95.0,
        "default_threshold_warn": 90.0,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "RECORD AGE <= 7d",
            "expectation": "95.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "record_age",
                "date_column": "__COLUMN__",
                "max_age": "7d",
                "threshold_pass": 95.0,
                "threshold_warn": 90.0,
            },
        },
    },
    {
        "dimension": "timeliness",
        "name": "ETL Processing Latency",
        "description": "Measures delay between event timestamp and load timestamp. Use for ETL pipeline monitoring.",
        "category": "timeliness_latency",
        "tags": ["latency", "etl", "pipeline"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "LATENCY <= 2h",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "latency",
                "timestamp_column": "__COLUMN__",
                "comparison_timestamp": "__COLUMN_2__",
                "max_age": "2h",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "timeliness",
        "name": "Processing Delay Check",
        "description": "Measures time between receipt and processing of records. Use for SLA monitoring on data pipelines.",
        "category": "timeliness_processing",
        "tags": ["processing_delay", "sla", "pipeline"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "PROCESSING DELAY <= 1h",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "processing_delay",
                "timestamp_column": "__COLUMN__",
                "comparison_timestamp": "__COLUMN_2__",
                "max_age": "1h",
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "timeliness",
        "name": "Delivery Window Compliance",
        "description": "Validates that data arrives within a scheduled delivery window. Use for batch file delivery SLAs.",
        "category": "timeliness_delivery",
        "tags": ["delivery_window", "schedule", "batch"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "WITHIN delivery window",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "delivery_window",
                "timestamp_column": "__COLUMN__",
                "delivery_window_start": "06:00",
                "delivery_window_end": "09:00",
                "threshold_pass": 100.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "timeliness",
        "name": "Data Heartbeat Monitor",
        "description": "Validates that data arrives at an expected frequency. Use for streaming or periodic batch data.",
        "category": "timeliness_heartbeat",
        "tags": ["heartbeat", "frequency", "monitoring"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": None,
        "canonical_rule_template": {
            "dimension": "timeliness",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "HEARTBEAT every 1h",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__"],
                "timeliness_type": "heartbeat",
                "timestamp_column": "__COLUMN__",
                "expected_frequency": "1h",
                "threshold_pass": 100.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# ACCURACY TEMPLATES (5)
# ---------------------------------------------------------------------------

_ACCURACY_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "accuracy",
        "name": "Reference Data Comparison",
        "description": "Compares column values to a reference/master table. Use for verifying product codes, customer names against golden source.",
        "category": "accuracy_reference",
        "tags": ["reference", "master_data", "golden_source"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "accuracy",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "MATCHES reference data",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "accuracy_type": "reference_comparison",
                "reference_dataset": "__REF_TABLE__",
                "reference_column": "__REF_COLUMN__",
                "join_keys": ["__COLUMN_2__"],
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "accuracy",
        "name": "Trusted Source Validation",
        "description": "Validates multiple columns against a trusted source by joining. Use for billing verification, address validation.",
        "category": "accuracy_trusted",
        "tags": ["trusted_source", "multi_column", "verification"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "accuracy",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "MATCHES trusted source",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "accuracy_type": "trusted_source",
                "reference_dataset": "__REF_TABLE__",
                "join_keys": ["__COLUMN_2__"],
                "comparison_columns": ["__COLUMN__"],
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "accuracy",
        "name": "Tolerated Deviation Check",
        "description": "Ensures values are within a tolerance of a reference column. Use for pricing, measurement, or financial reconciliation.",
        "category": "accuracy_tolerance",
        "tags": ["deviation", "tolerance", "financial"],
        "default_severity": "high",
        "default_threshold_pass": 98.0,
        "default_threshold_warn": 95.0,
        "canonical_rule_template": {
            "dimension": "accuracy",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "WITHIN tolerance of reference",
            "expectation": "98.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "accuracy_type": "tolerated_deviation",
                "reference_dataset": "__REF_TABLE__",
                "reference_column": "__COLUMN_2__",
                "join_keys": ["__COLUMN_2__"],
                "tolerance_type": "percentage",
                "tolerance_value": 5.0,
                "threshold_pass": 98.0,
                "threshold_warn": 95.0,
            },
        },
    },
    {
        "dimension": "accuracy",
        "name": "Statistical Outlier Detection (Z-Score)",
        "description": "Detects outlier values using Z-score method (>3σ from mean). Use for transaction amounts, sensor readings.",
        "category": "accuracy_statistical",
        "tags": ["outlier", "z_score", "anomaly"],
        "default_severity": "medium",
        "default_threshold_pass": 99.0,
        "default_threshold_warn": 97.0,
        "canonical_rule_template": {
            "dimension": "accuracy",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "Z-SCORE within threshold",
            "expectation": "99.0%",
            "severity": "medium",
            "parameters": {
                "columns": ["__COLUMN__"],
                "accuracy_type": "statistical",
                "method": "z_score",
                "threshold": 3.0,
                "threshold_pass": 99.0,
                "threshold_warn": 97.0,
            },
        },
    },
    {
        "dimension": "accuracy",
        "name": "Derived Value Validation",
        "description": "Validates that a column matches a calculated value from a formula. Use for computed columns, ETL transformations.",
        "category": "accuracy_derived",
        "tags": ["derived", "formula", "calculated"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "accuracy",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "EQUALS derived value",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "accuracy_type": "derived_value",
                "formula": "__EXPRESSION__",
                "tolerance_type": "absolute",
                "tolerance_value": 0.01,
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# RECONCILIATION TEMPLATES (6)
# ---------------------------------------------------------------------------

_RECONCILIATION_TEMPLATES: list[dict[str, Any]] = [
    {
        "dimension": "reconciliation",
        "name": "Record Count Match",
        "description": "Validates that two datasets have the same number of records. Use for ETL row count reconciliation.",
        "category": "reconciliation_count",
        "tags": ["record_count", "etl", "row_count"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": None,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__",
            "condition": "COUNT matches",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "record_count",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "threshold_pass": 100.0,
            },
        },
    },
    {
        "dimension": "reconciliation",
        "name": "One-to-One Record Mapping",
        "description": "Validates that every record in dataset1 has exactly one match in dataset2 on join keys. Use for migration verification.",
        "category": "reconciliation_mapping",
        "tags": ["one_to_one", "migration", "mapping"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__",
            "condition": "1:1 mapping on join key",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "one_to_one",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "join_keys": ["__COLUMN__"],
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "reconciliation",
        "name": "Aggregate Total Reconciliation",
        "description": "Validates that SUM/COUNT of a column matches between two datasets. Use for financial reconciliation (GL vs sub-ledger).",
        "category": "reconciliation_aggregate",
        "tags": ["aggregate", "financial", "general_ledger"],
        "default_severity": "critical",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "SUM matches across datasets",
            "expectation": "100.0%",
            "severity": "critical",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "aggregate",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "aggregate_column": "__COLUMN__",
                "aggregate_function": "SUM",
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "reconciliation",
        "name": "Field-Level Value Comparison",
        "description": "Compares individual field values between matched records in two datasets. Use for post-migration data validation.",
        "category": "reconciliation_field",
        "tags": ["field_level", "comparison", "migration"],
        "default_severity": "high",
        "default_threshold_pass": 99.0,
        "default_threshold_warn": 98.0,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "FIELD VALUES match",
            "expectation": "99.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "field_level",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "join_keys": ["__COLUMN_2__"],
                "compare_columns": ["__COLUMN__"],
                "threshold_pass": 99.0,
                "threshold_warn": 98.0,
            },
        },
    },
    {
        "dimension": "reconciliation",
        "name": "Tolerance-Based Reconciliation",
        "description": "Allows a small variance (percentage or absolute) when comparing datasets. Use for financial data with rounding differences.",
        "category": "reconciliation_tolerance",
        "tags": ["tolerance", "variance", "rounding"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "WITHIN tolerance",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "aggregate",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "aggregate_column": "__COLUMN__",
                "aggregate_function": "SUM",
                "tolerance_type": "percentage",
                "tolerance_value": 0.01,
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
    {
        "dimension": "reconciliation",
        "name": "Missing and Extra Record Detection",
        "description": "Identifies records present in one dataset but missing from the other. Use for data completeness between systems.",
        "category": "reconciliation_coverage",
        "tags": ["missing", "extra", "coverage"],
        "default_severity": "high",
        "default_threshold_pass": 100.0,
        "default_threshold_warn": 99.0,
        "canonical_rule_template": {
            "dimension": "reconciliation",
            "entity": "__TABLE__.__COLUMN__",
            "condition": "NO missing or extra records",
            "expectation": "100.0%",
            "severity": "high",
            "parameters": {
                "columns": ["__COLUMN__"],
                "reconciliation_type": "missing_extra",
                "source_dataset": "__TABLE__",
                "target_dataset": "__REF_TABLE__",
                "join_keys": ["__COLUMN__"],
                "threshold_pass": 100.0,
                "threshold_warn": 99.0,
            },
        },
    },
]

# ---------------------------------------------------------------------------
# Combined list
# ---------------------------------------------------------------------------

SEED_TEMPLATES: list[dict[str, Any]] = (
    _COMPLETENESS_TEMPLATES
    + _VALIDITY_TEMPLATES
    + _UNIQUENESS_TEMPLATES
    + _CONFORMITY_TEMPLATES
    + _CONSISTENCY_TEMPLATES
    + _TIMELINESS_TEMPLATES
    + _ACCURACY_TEMPLATES
    + _RECONCILIATION_TEMPLATES
)


def seed_all(db: Session) -> int:
    """
    Insert all seed templates that don't already exist (idempotent by name).

    Returns the number of newly inserted templates.
    """
    existing_names = {row[0] for row in db.query(RuleTemplate.name).all()}

    inserted = 0
    for tpl in SEED_TEMPLATES:
        if tpl["name"] in existing_names:
            continue
        obj = RuleTemplate(
            dimension=tpl["dimension"],
            name=tpl["name"],
            description=tpl["description"],
            category=tpl["category"],
            tags=tpl.get("tags", []),
            canonical_rule_template=tpl["canonical_rule_template"],
            default_severity=tpl.get("default_severity", "high"),
            default_threshold_pass=tpl.get("default_threshold_pass", 98.0),
            default_threshold_warn=tpl.get("default_threshold_warn"),
            use_count=0,
            is_active=True,
        )
        db.add(obj)
        inserted += 1

    if inserted:
        db.commit()

    return inserted
