/**
 * Validity Dimension Schema — 8 subtypes
 * Registered on import.
 */
import { registerDimension } from './registry-store'
import type { DimensionSchema } from './types'

const schema: DimensionSchema = {
  dimension: 'validity',
  defaultSubtype: 'allowed_values',
  subtypes: [
    {
      subtype: 'allowed_values',
      label: 'Allowed Values',
      description: 'Values must be within a defined set',
      requiresReferenceData: false,
      fields: [
        {
          key: 'allowed_values',
          label: 'Allowed Values',
          helpText: 'Enter allowed values. Press Enter to add, paste comma-separated.',
          inputType: 'tag-input',
          required: true,
          defaultValue: [],
          section: 'businessLogic',
          placeholder: 'Add an allowed value…',
        },
        {
          key: 'case_sensitive',
          label: 'Case Sensitive',
          helpText: 'Compare values with exact case matching',
          inputType: 'toggle',
          required: false,
          defaultValue: false,
          section: 'businessLogic',
        },
      ],
      defaultConfig: () => ({ allowed_values: [], case_sensitive: false }),
    },
    {
      subtype: 'range',
      label: 'Range Check',
      description: 'Values must be within a numeric range',
      requiresReferenceData: false,
      fields: [
        {
          key: 'min_value',
          label: 'Minimum Value',
          helpText: 'Lower bound of the valid range',
          inputType: 'number',
          required: false,
          defaultValue: null,
          section: 'businessLogic',
          placeholder: 'No minimum',
        },
        {
          key: 'max_value',
          label: 'Maximum Value',
          helpText: 'Upper bound of the valid range',
          inputType: 'number',
          required: false,
          defaultValue: null,
          section: 'businessLogic',
          placeholder: 'No maximum',
        },
        {
          key: 'inclusive_min',
          label: 'Inclusive Minimum',
          helpText: 'Include the minimum value as valid (>=)',
          inputType: 'toggle',
          required: false,
          defaultValue: true,
          section: 'businessLogic',
        },
        {
          key: 'inclusive_max',
          label: 'Inclusive Maximum',
          helpText: 'Include the maximum value as valid (<=)',
          inputType: 'toggle',
          required: false,
          defaultValue: true,
          section: 'businessLogic',
        },
      ],
      defaultConfig: () => ({
        min_value: null,
        max_value: null,
        inclusive_min: true,
        inclusive_max: true,
      }),
    },
    {
      subtype: 'regex',
      label: 'Pattern Match (Regex)',
      description: 'Values must match a regular expression',
      requiresReferenceData: false,
      fields: [
        {
          key: 'pattern',
          label: 'Regex Pattern',
          helpText: 'Regular expression that values must match',
          inputType: 'expression',
          required: true,
          defaultValue: '',
          section: 'businessLogic',
          placeholder: 'e.g. ^[A-Z]{2}[0-9]{4}$',
        },
      ],
      defaultConfig: () => ({ pattern: '' }),
    },
    {
      subtype: 'reference_lookup',
      label: 'Reference Lookup',
      description: 'Values must exist in a reference dataset column',
      requiresReferenceData: true,
      fields: [
        {
          key: 'reference_column',
          label: 'Reference Column',
          helpText: 'Column in the reference dataset to look up values against',
          inputType: 'text',
          required: true,
          defaultValue: '',
          section: 'referenceData',
        },
      ],
      defaultConfig: () => ({ reference_column: '' }),
    },
    {
      subtype: 'business_rule',
      label: 'Business Rule',
      description: 'Values must satisfy a custom business rule expression',
      requiresReferenceData: false,
      fields: [
        {
          key: 'business_rule_expression',
          label: 'Business Rule Expression',
          helpText: 'Expression that must evaluate to true for valid rows',
          inputType: 'expression',
          required: true,
          defaultValue: '',
          section: 'businessLogic',
          placeholder: 'e.g. amount > 0 AND status != "cancelled"',
        },
      ],
      defaultConfig: () => ({ business_rule_expression: '' }),
    },
    {
      subtype: 'cross_field',
      label: 'Cross-Field Validation',
      description: 'Compare a column against another column in the same row',
      requiresReferenceData: false,
      fields: [
        {
          key: 'comparison_column',
          label: 'Comparison Column',
          helpText: 'The other column to compare against',
          inputType: 'column-picker',
          required: true,
          defaultValue: '',
          section: 'businessLogic',
        },
        {
          key: 'comparison_operator',
          label: 'Comparison Operator',
          helpText: 'How to compare the two columns',
          inputType: 'dropdown',
          required: true,
          defaultValue: 'equals',
          section: 'businessLogic',
          options: [
            { value: 'equals', label: 'Equals (=)' },
            { value: 'not_equals', label: 'Not Equals (≠)' },
            { value: 'greater_than', label: 'Greater Than (>)' },
            { value: 'less_than', label: 'Less Than (<)' },
            { value: 'greater_equal', label: 'Greater or Equal (≥)' },
            { value: 'less_equal', label: 'Less or Equal (≤)' },
          ],
        },
      ],
      defaultConfig: () => ({
        comparison_column: '',
        comparison_operator: 'equals',
      }),
    },
    {
      subtype: 'date_logic',
      label: 'Date Logic',
      description: 'Validate date relationships between columns',
      requiresReferenceData: false,
      fields: [
        {
          key: 'comparison_column',
          label: 'Comparison Date Column',
          helpText: 'The date column to compare against',
          inputType: 'column-picker',
          required: true,
          defaultValue: '',
          section: 'businessLogic',
        },
        {
          key: 'date_operator',
          label: 'Date Operator',
          helpText: 'Temporal relationship between the columns',
          inputType: 'dropdown',
          required: true,
          defaultValue: 'before',
          section: 'businessLogic',
          options: [
            { value: 'before', label: 'Before' },
            { value: 'after', label: 'After' },
            { value: 'same_day', label: 'Same Day' },
            { value: 'within', label: 'Within Duration' },
          ],
        },
      ],
      defaultConfig: () => ({
        comparison_column: '',
        date_operator: 'before',
      }),
    },
    {
      subtype: 'negative',
      label: 'Negative Pattern',
      description: 'Values must NOT match a given pattern or set',
      requiresReferenceData: false,
      fields: [
        {
          key: 'negative_pattern',
          label: 'Pattern to Reject',
          helpText: 'Expression or regex that values must NOT match',
          inputType: 'expression',
          required: true,
          defaultValue: '',
          section: 'businessLogic',
          placeholder: 'e.g. ^TEST.*',
        },
        {
          key: 'negative_match_mode',
          label: 'Match Mode',
          helpText: 'How to interpret the pattern',
          inputType: 'radio',
          required: true,
          defaultValue: 'regex',
          section: 'businessLogic',
          options: [
            { value: 'regex', label: 'Regular Expression' },
            { value: 'exact', label: 'Exact Match' },
            { value: 'contains', label: 'Contains' },
          ],
        },
      ],
      defaultConfig: () => ({
        negative_pattern: '',
        negative_match_mode: 'regex',
      }),
    },
  ],
}

registerDimension(schema)
